MYHOSTNAME="ubuntu-sdb-homework-12-06-vm"
MYIP_SUBNET="192.168.120.6"
SERVERS=[
  {
    :number => "1",
    :hostname => MYHOSTNAME+"1",
    :ip => MYIP_SUBNET+"1",
    :ram => "2048",
    :cpus => 2
  },
  {
    :number => "2",
    :hostname => MYHOSTNAME+"2",
    :ip => MYIP_SUBNET+"2",
    :ram => "2048",
    :cpus => 2
  }
]
Vagrant.configure("2") do |config|
  SERVERS.each do |machine|
    config.vm.define machine[:hostname] do |node|
      #node.vm.box = "ubuntu/bionic64"
      node.vm.box = "ubuntu/focal64"
      node.vm.host_name = machine[:hostname]
      node.vm.provider :virtualbox do |vb|
        vb.name = machine[:hostname]
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.cpus = machine[:cpus]
        vb.memory = machine[:ram]
      end
      node.vm.provision "shell", path: "autorun" + machine[:number] + ".sh"
      #node.vm.provision "shell", inline: <<-SHELL
      #apt-get update
      #apt install -y mysql-server mysql-client
#SHELL
    end
  end
end
